    #Lists in use for poem completion
Noun_Object_plural = ['actor', 'gold', 'painting', 'advertisement', 'grass', 'parrot', 'afternoon', 'pencil', 'guitar', 'piano', 'ambulance', 'hair', 'pillow', 'animal', 'hamburger', 'pizza', 'answer', 'helicopter', 'planet', 'apple', 'helmet', 'plastic', 'army', 'holiday', 'honey', 'potato', 'balloon', 'horse', 'queen', 'banana', 'quill', 'battery', 'house', 'rain', 'hydrogen', 'rainbow', 'beard', 'ice', 'raincoat', 'insect', 'insurance', 'boy', 'iron', 'river', 'branch', 'rocket', 'breakfast', 'jackal', 'brother', 'jelly', 'rose', 'camera', 'jewellery', 'candle', 'sandwich', 'car', 'juice', 'kangaroo', 'scooter', 'carpet', 'king', 'shampoo', 'cartoon', 'shoe', 'kite', 'soccer', 'church', 'knife', 'spoon', 'crayon', 'lamp', 'stone', 'crowd', 'lawyer', 'sugar', 'daughter', 'leather', 'death', 'teacher', 'lighter', 'telephone', 'diamond', 'lion', 'television', 'dinner', 'lizard', 'tent', 'disease', 'lock', 'doctor', 'london', 'tomato', 'dog', 'toothbrush', 'dream', 'machine', 'traffic', 'dress', 'magazine', 'train', 'magician', 'truck', 'egg', 'eggplant', 'market', 'umbrella', 'match', 'van', 'elephant', 'microphone', 'vase', 'energy', 'monkey', 'vegetable', 'engine', 'morning', 'vulture', 'england', 'motorcycle', 'wall', 'evening', 'nail', 'whale', 'eye', 'napkin', 'window', 'family', 'needle', 'wire', 'nest', 'xylophone', 'fish', 'yacht', 'flag', 'night', 'yak', 'flower', 'notebook', 'zebra', 'footballs', 'ocean', 'zoo', 'forest', 'oil', 'fountains', 'oranges','gas','oxygen', 'girls', 'furniture', 'oysters', 'glasses', 'ghosts''chairs','peaches', 'plums','convertible']
Past_Simple_Verb = ['brought','bought', 'caught', 'drunk', 'sunk', 'sung', 'chosen', 'lost', 'frozen', 'bled', 'fed', 'read', 'blown', 'grown', 'flown', 'delt', 'felt', 'kept', 'bet', 'cut', 'set', 'arisen', 'babysat', 'been', 'beaten', 'become', 'begun', 'bent', 'bet', 'bound', 'bitten', 'bled', 'blown', 'broken', 'bred', 'brought', 'broadcast', 'built', 'bought', 'caught', 'chosen', 'come', 'cost', 'cut', 'dealt', 'dug', 'done', 'drawn', 'drunk', 'driven', 'eaten', 'fallen', 'fed', 'felt', 'fought', 'found', 'flown', 'forbidden', 'forgotten', 'forgiven', 'frozen', 'got', 'gotten','given', 'gone', 'grown', 'hung', 'had', 'heard', 'hidden', 'hit', 'held', 'hurt', 'kept', 'known', 'laid', 'led', 'left', 'lent', 'let', 'lain', 'lit', 'lost', 'made', 'meant', 'met', 'paid', 'put','quit', 'read', 'ridden', 'rung', 'risen', 'run', 'said', 'seen', 'sold', 'sent','shaken', 'shone', 'shot', 'shown','shut','sung', 'sunk', 'sat', 'slept', 'slid', 'spoken', 'sped', 'spent', 'spun', 'spread', 'stood', 'stolen', 'stuck', 'stung', 'struck', 'sworn', 'swept','swum','swung','taken','taught','torn','told','thought','thrown','understood','woken','worn','won','withdrawn','written']
Meal_Occasion = ['breakfast','Lunch','samhein','easter','dinner','brunch','elevenses','tea','supper']
Direction = ['under','above', 'inside', 'surrounding']
Container = ['fridge','hospital','Airport','island','school','bed','beach','refrigerator','library','restaurant','caravan','room','garage','kitchen','Garden','freezer','loot chest', 'cupboard']
Adjective = ['adorable', 'adventurous', 'aggressive', 'agreeable', 'alert', 'alive', 'amused', 'angry', 'annoyed', 'annoying', 'anxious', 'arrogant', 'ashamed', 'attractive', 'average', 'awful', 'bad', 'beautiful', 'better', 'bewildered', 'black', 'bloody', 'blue', 'blue-eyed', 'blushing', 'bored', 'brainy', 'brave', 'breakable', 'bright', 'busy', 'calm', 'careful', 'cautious', 'charming', 'cheerful', 'clean', 'clear', 'clever', 'cloudy', 'clumsy', 'colorful', 'combative', 'comfortable', 'concerned', 'condemned', 'confused', 'cooperative', 'courageous', 'crazy', 'creepy', 'crowded', 'cruel', 'curious', 'cute', 'dangerous', 'dark', 'dead', 'defeated', 'defiant', 'delightful', 'depressed', 'determined', 'different', 'difficult', 'disgusted', 'distinct', 'disturbed', 'dizzy', 'doubtful', 'drab', 'dull', 'eager', 'easy', 'elated', 'elegant', 'embarrassed', 'enchanting', 'encouraging', 'energetic', 'enthusiastic', 'envious', 'evil', 'excited', 'expensive', 'exuberant', 'fair', 'faithful', 'famous', 'fancy', 'fantastic', 'fierce', 'filthy', 'fine', 'foolish', 'fragile', 'frail', 'frantic', 'friendly', 'frightened', 'funny', 'gentle', 'gifted', 'glamorous', 'gleaming', 'glorious', 'good', 'gorgeous', 'graceful', 'grieving', 'grotesque', 'grumpy', 'handsome', 'happy', 'healthy', 'helpful', 'helpless', 'hilarious', 'homeless', 'homely', 'horrible', 'hungry', 'hurt', 'ill', 'important', 'impossible', 'inexpensive', 'innocent', 'inquisitive', 'itchy', 'jealous', 'jittery', 'jolly', 'joyous', 'kind', 'lazy', 'light', 'lively', 'lonely', 'long', 'lovely', 'lucky', 'magnificent', 'misty', 'modern', 'motionless', 'muddy', 'mushy', 'mysterious', 'nasty', 'naughty', 'nervous', 'nice', 'nutty', 'obedient', 'obnoxious', 'odd', 'old-fashioned', 'open', 'outrageous', 'outstanding', 'panicky', 'perfect', 'plain', 'pleasant', 'poised', 'poor', 'powerful', 'precious', 'prickly', 'proud', 'putrid', 'puzzled', 'quaint', 'real', 'relieved', 'repulsive', 'rich', 'scary', 'selfish', 'shiny', 'shy', 'silly', 'sleepy', 'smiling', 'smoggy', 'sore', 'sparkling', 'splendid', 'spotless', 'stormy', 'strange', 'stupid', 'successful', 'super', 'talented', 'tame', 'tasty', 'tender', 'tense', 'terrible', 'thankful', 'thoughtful', 'thoughtless', 'tired', 'tough', 'troubled', 'ugliest', 'ugly', 'uninterested', 'unsightly', 'unusual', 'upset', 'uptight', 'vast', 'victorious', 'vivacious', 'wandering', 'weary', 'wicked', 'wide-eyed', 'wild', 'witty', 'worried', 'worrisome', 'wrong', 'zany', 'zealous']





